# Generated by Django 4.1.3 on 2022-11-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('dt_cad', models.DateTimeField(verbose_name='Data de cadastro')),
            ],
            options={
                'ordering': ['dt_cad'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=260, verbose_name='Descrição')),
                ('unidade', models.IntegerField(choices=[(1, 'Kilos'), (2, 'Litros'), (3, 'Und'), (4, 'Metro')], default=3, verbose_name='Unidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estoque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('foto', models.ImageField(upload_to='catalogo_img')),
                ('dt_cad', models.DateTimeField(verbose_name='Data de cadastro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipo')),
            ],
            options={
                'ordering': ['dt_cad'],
            },
        ),
    ]
